nodes: 8
tasks_per_node: 8
tag: in1k-16f
eval_name: image_classification_frozen
resume_checkpoint: true
data:
  root_path: //network/scratch/s/sonia.joseph/datasets/kaggle_datasets/ILSVRC/Data/CLS-LOC/
  image_folder: imagenet_full_size/061417/
  num_classes: 1000
  resolution: 224
  dataset_name: ImageNet
optimization:
  num_epochs: 21
  batch_size: 16
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_large
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  folder: /network/scratch/s/sonia.joseph/jepa_models/github_models/vit-l-16
  checkpoint: vitl16.pth.tar # name of pretrained model file inside folder
  write_tag: jepa
